import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">

      <body className={inter.className}>
      <header>
          <nav className="bg-orange-800  font-mono font-bold flex gap-11 justify-start py-5 ">
            <Link href="/chai">Chai </Link>
            
            <Link href="/accordion">Accordion</Link>
          </nav>
        </header>
        {children}</body>
    </html>
  );
}
